version: "3.7"
services:
  nginx:
    container_name: api_nginx
    image: modelfak23/shop-nginx
    volumes:
      - ./.logs/nginx:/var/log/nginx
      - ./app-php:/var/www/html
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/sites/:/etc/nginx/sites-available
      - ./containers/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443