version: "3.7"
services:
  client:
    container_name: client
    build:
      context: ./app/client
    volumes:
      -  ./app/client:/home/node/app:rw
      - /home/node/app/node_modules
    ports:
      - 8080:3000
    command: npm start
    depends_on:
      - server
    environment:
      - NODE_ENV=development
  server:
    container_name: server
    build:
      context: ./app/server
    volumes:
      -  ./app/server:/home/node/app:rw
      - /home/node/app/node_modules
    ports:
      - 3000:8080
    command: npm start