
export const CRYPTOCURRENCY_INIT = 'CRYPTOCURRENCY_INIT';
export const CRYPTOCURRENCY_START = 'CRYPTOCURRENCY_START';
export const CRYPTOCURRENCY_SUCCESS = 'CRYPTOCURRENCY_SUCCESS';
export const CRYPTOCURRENCY_FAIL = 'CRYPTOCURRENCY_FAIL';
export const CRYPTOCURRENCY_SELECT = 'CRYPTOCURRENCY_SELECT';
export const CRYPTOCURRENCY_SET = 'CRYPTOCURRENCY_SET';

export const CALCULATOR_CALCULATE = 'CALCULATOR_CALCULATE';
export const CALCULATOR_SET_RESULT = 'CALCULATOR_SET_RESULT';


