
export const CRYPTOCURRENCY_INIT = 'CRYPTOCURRENCY_INIT';
export const CRYPTOCURRENCY_START = 'CRYPTOCURRENCY_START';
export const CRYPTOCURRENCY_SUCCESS = 'CRYPTOCURRENCY_SUCCESS';
export const CRYPTOCURRENCY_FAIL = 'CRYPTOCURRENCY_FAIL';
export const CRYPTOCURRENCY_SELECT = 'CRYPTOCURRENCY_SELECT';
